--------------------------------------------------------
--  File created - Tuesday-January-29-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LIBRARY_
--------------------------------------------------------

  CREATE TABLE "PRACTICAS"."LIBRARY_" 
   (	"ID_LIBRARY" NUMBER, 
	"NAME_LIBRARY" VARCHAR2(100 BYTE), 
	"EMPLOYEE" VARCHAR2(100 BYTE), 
	"LOAN_DATE" VARCHAR2(100 BYTE), 
	"DELIVER_DATE" VARCHAR2(100 BYTE), 
	"USER_LIBRARY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PRACTICAS.LIBRARY_
SET DEFINE OFF;
Insert into PRACTICAS.LIBRARY_ (ID_LIBRARY,NAME_LIBRARY,EMPLOYEE,LOAN_DATE,DELIVER_DATE,USER_LIBRARY) values (1,'Ciencia','Ramiro','10Abril','15Abril','Lucas');
Insert into PRACTICAS.LIBRARY_ (ID_LIBRARY,NAME_LIBRARY,EMPLOYEE,LOAN_DATE,DELIVER_DATE,USER_LIBRARY) values (2,'Historia','Alberto','1Mayo','5Mayo','Javier');
